on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: cachix/cachix-action@v15
        with:
          name: callumio-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(nerdfonts)'
          extraPullNames: nix-community, om
      - run: nix run github:juspay/omnix --accept-flake-config -- ci run "."
