on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: cachix/cachix-action@v16
        with:
          name: callumio-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(nerdfonts)'
          extraPullNames: nix-community, om
      - run: nix build github:srid/devour-flake -L --no-link --print-out-paths --override-input flake .

